services:
  vh-warp:
    image: uxiaohan/vh-warp:latest
    container_name: vh-warp
    restart: always
    ports:
      - "1111:1111"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp-data:/var/lib/cloudflare-warp

volumes:
  warp-data:
