services:
  vh-warp:
    build:
      context: .
      args:
        - GITHUB_PROXY=${GITHUB_PROXY:-}
    container_name: vh-warp
    restart: unless-stopped
    ports:
      - "1111:1111"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - warp-data:/var/lib/cloudflare-warp

volumes:
  warp-data: