services:
  vh-warp:
    build:
      context: .
      args:
        - GITHUB_PROXY=${GITHUB_PROXY:-}
    container_name: vh-warp
    restart: unless-stopped
    ports:
      - "1111:1111"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
      - MKNOD
    device_cgroup_rules:
      - "c 10:200 rwm"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.core.somaxconn=65535
    volumes:
      - warp-data:/var/lib/cloudflare-warp

volumes:
  warp-data: